// ARRAY PRODUTOS
// ADICIONAR PRODUTOS AQUI
// As imagens ficam em js/galerias.js e sao associadas pelo id do produto.
export const produtos = [
  {
  id: 1,
  nome: "Smartwatch Aurafit Trek 2",
  categoria: "Tecnologia",
  preco: "R$ 351,96",
  precoNumero: 351.96,
  estrelas: 4.8,
  descricaoCurta: "Tela moderna, funções fitness e chamadas.",
  descricaoLonga: "Smartwatch completo com monitoramento de saúde, notificações inteligentes e design esportivo para rotina ativa.",
  linkAfiliado: "https://meli.la/1yUTfTV",
  meliId:"MLB6419155018",
},

{
  id: 2,
  nome: "Amazfit Active 2 Smartwatch",
  categoria: "Tecnologia",
  preco: "R$ 749,00",
  precoNumero: 749,
  estrelas: 4.9,
  descricaoCurta: "Premium, preciso e bateria duradoura.",
  descricaoLonga: "Relógio inteligente avançado com excelente construção, sensores precisos e recursos ideais para saúde e desempenho.",
  linkAfiliado: "https://meli.la/1m7s2UG",
  meliId: "MLB4508627623",
},

{
  id: 3,
  nome: "Ring Light Mesa Tomate",
  categoria: "Tecnologia",
  preco: "R$ 360,04",
  precoNumero: 360.04,
  estrelas: 4.7,
  descricaoCurta: "Iluminação ideal para mesa e gravações.",
  descricaoLonga: "Ring light com suporte prático para criadores de conteúdo, chamadas de vídeo e maquiagem profissional.",
  linkAfiliado: "https://meli.la/2S4f4Ps",
  meliId: "MLB3950821473",
},

{
  id: 4,
  nome: "Kit Youtuber Completo",
  categoria: "Tecnologia",
  preco: "R$ 142,65",
  precoNumero: 142.65,
  estrelas: 4.6,
  descricaoCurta: "Kit ideal para começar a gravar.",
  descricaoLonga: "Conjunto pensado para vídeos, lives e redes sociais com acessórios essenciais para melhor produção.",
  linkAfiliado: "https://meli.la/2hdqpp9",
  meliId: "MLB5420720986",
},

{
  id: 5,
  nome: "Ring Light B&G",
  categoria: "Tecnologia",
  preco: "R$ 29,99",
  precoNumero: 29.99,
  estrelas: 4.4,
  descricaoCurta: "Compacto, útil e ótimo custo-benefício.",
  descricaoLonga: "Iluminação prática para selfies, chamadas de vídeo e conteúdo diário com preço acessível.",
  linkAfiliado: "https://meli.la/1t57Q6X",
  meliId: "MLB62772025",
},

{
  id: 6,
  nome: "Ring Light LED Profissional",
  categoria: "Tecnologia",
  preco: "R$ 180,49",
  precoNumero: 180.49,
  estrelas: 4.8,
  descricaoCurta: "Iluminação forte e acabamento premium.",
  descricaoLonga: "Modelo profissional para gravações, estúdio caseiro, maquiagem e criação de conteúdo com alta qualidade.",
  linkAfiliado: "https://meli.la/1ndAP8S",
  meliId: "MLB4279130217",
},

{
  id: 8,
  nome: "Power Bank Magnético",
  categoria: "Tecnologia",
  preco: "R$ 40,39",
  precoNumero: 40.39,
  estrelas: 4.4,
  descricaoCurta: "Energia extra com fixação magnética.",
  descricaoLonga: "Carregador portátil prático para manter seu celular carregado no dia a dia.",
  linkAfiliado: "https://meli.la/2yV7ca1",
  meliId: "MLB23156368",
},

{
  id: 9,
  nome: "Carregador MagSafe Sem Fio",
  categoria: "Tecnologia",
  preco: "R$ 46,15",
  precoNumero: 46.15,
  estrelas: 4.5,
  descricaoCurta: "Carregamento por indução prático.",
  descricaoLonga: "Modelo magnético compatível com tecnologia sem fio para mais praticidade e organização.",
  linkAfiliado: "https://meli.la/1E71j6K",
  meliId: "MLB6194512168",
},

{
  id: 10,
  nome: "Carregador Portátil Indução",
  categoria: "Tecnologia",
  preco: "R$ 479,00",
  precoNumero: 479,
  estrelas: 4.7,
  descricaoCurta: "Alta capacidade e sem fios.",
  descricaoLonga: "Power bank premium com carregamento por indução para máxima praticidade.",
  linkAfiliado: "https://meli.la/2Cqxufj",
  meliId: "MLB42134938",
},

{
  id: 11,
  nome: "Basike Carregador Sem Fio",
  categoria: "Tecnologia",
  preco: "R$ 160,00",
  precoNumero: 160,
  estrelas: 4.6,
  descricaoCurta: "Design moderno e carga eficiente.",
  descricaoLonga: "Carregador wireless ideal para mesa de trabalho, quarto ou setup limpo.",
  linkAfiliado: "https://meli.la/27hp8Ek",
  meliId: "MLB59194795",
},

{
  id: 12,
  nome: "Carregador Turbo Magnético",
  categoria: "Tecnologia",
  preco: "R$ 34,35",
  precoNumero: 34.35,
  estrelas: 4.4,
  descricaoCurta: "Turbo, sem fio e magnético.",
  descricaoLonga: "Carregamento rápido com encaixe magnético para uso prático e portátil.",
  linkAfiliado: "https://meli.la/189v6RC",
  meliId: "MLB40232351",
},

{
  id: 13,
  nome: "Carregador Turbo 125W",
  categoria: "Tecnologia",
  preco: "R$ 76,64",
  precoNumero: 76.64,
  estrelas: 4.7,
  descricaoCurta: "Alta potência para recarga rápida.",
  descricaoLonga: "Ideal para quem precisa de velocidade e eficiência no carregamento diário.",
  linkAfiliado: "https://meli.la/23zPNF6",
  meliId: "MLB4357220635",
},

{
  id: 15,
  nome: "Power Bank 50.000mAh Turbo",
  categoria: "Tecnologia",
  preco: "R$ 133,86",
  precoNumero: 133.86,
  estrelas: 4.8,
  descricaoCurta: "Gigante em bateria e autonomia.",
  descricaoLonga: "Ideal para viagens, rotina intensa e emergências com múltiplas recargas.",
  linkAfiliado: "https://meli.la/1fLmPwC",
  meliId: "MLB5588364980",
},

{
  id: 16,
  nome: "Carregador Turbo 120W",
  categoria: "Tecnologia",
  preco: "R$ 26,00",
  precoNumero: 26,
  estrelas: 4.6,
  descricaoCurta: "Potência forte e preço baixo.",
  descricaoLonga: "Modelo turbo para quem busca rapidez no carregamento sem gastar muito.",
  linkAfiliado: "https://meli.la/2UUFrPW",
  meliId: "MLB67421753",
},

{
  id: 17,
  nome: "Power Bank 20000mAh 22.5W",
  categoria: "Tecnologia",
  preco: "R$ 69,90",
  precoNumero: 69.90,
  estrelas: 4.6,
  descricaoCurta: "Capacidade alta e carga rápida.",
  descricaoLonga: "Excelente equilíbrio entre tamanho, autonomia e velocidade para o dia a dia.",
  linkAfiliado: "https://meli.la/2vj4FXx",
  meliId: "MLB66174362",
},

{
  id: 18,
  nome: "Basike GaN 100W",
  categoria: "Tecnologia",
  preco: "R$ 261,00",
  precoNumero: 261,
  estrelas: 4.8,
  descricaoCurta: "Tecnologia GaN potente e compacta.",
  descricaoLonga: "Carregador premium de alta potência para celular, notebook e múltiplos dispositivos.",
  linkAfiliado: "https://meli.la/188ruRh",
  meliId: "MLB62385376",
},

{
  id: 19,
  nome: "Carregador Turbo 40W",
  categoria: "Tecnologia",
  preco: "R$ 39,90",
  precoNumero: 39.9,
  estrelas: 4.5,
  descricaoCurta: "Rápido, prático e acessível.",
  descricaoLonga: "Boa escolha para quem quer carregamento eficiente com excelente custo-benefício.",
  linkAfiliado: "https://meli.la/11XJCCR",
  meliId: "MLB4233789327",
},

{
  id: 20,
  nome: "Relógio Smartwatch",
  categoria: "Tecnologia",
  preco: "R$ 170,23",
  precoNumero: 170.23,
  estrelas: 4.5,
  descricaoCurta: "Funções inteligentes no pulso.",
  descricaoLonga: "Receba notificações, acompanhe atividades físicas e modernize sua rotina.",
  linkAfiliado: "https://meli.la/2zTqei6",
  meliId: "MLB4635997716",
},

{
  id: 21,
  nome: "Smartwatch AMOLED",
  categoria: "Tecnologia",
  preco: "R$ 199,99",
  precoNumero: 199.99,
  estrelas: 4.7,
  descricaoCurta: "Tela premium com cores vibrantes.",
  descricaoLonga: "Display AMOLED com ótima visibilidade, estilo moderno e funções inteligentes.",
  linkAfiliado: "https://meli.la/2AFsbyK",
  meliId: "MLB65238613",
},

{
  id: 22,
  nome: "Smartwatch PEJE ZW10",
  categoria: "Tecnologia",
  preco: "R$ 182,00",
  precoNumero: 182,
  estrelas: 4.6,
  descricaoCurta: "Visual moderno e recursos úteis.",
  descricaoLonga: "Modelo completo com monitoramento diário, notificações e ótimo custo-benefício.",
  linkAfiliado: "https://meli.la/1g25jBn",
  meliId: "MLB57800264",
},
{
  id: 23,
  nome: "QCY T13x Bluetooth TWS",
  categoria: "Tecnologia",
  preco: "R$ 134,83",
  precoNumero: 134.83,
  estrelas: 4.8,
  descricaoCurta: "Graves fortes, baixa latência e ótima bateria.",
  descricaoLonga: "Fone sem fio com conexão estável Bluetooth, som equilibrado e microfone para chamadas claras. Ideal para uso diário.",
  linkAfiliado: "https://meli.la/2S87F7g",
  meliId: "MLB27616234",
},

{
  id: 24,
  nome: "JBL Tune 720BT Bluetooth",
  categoria: "Tecnologia",
  preco: "R$ 295,00",
  precoNumero: 295,
  estrelas: 4.9,
  descricaoCurta: "Som JBL Pure Bass e bateria duradoura.",
  descricaoLonga: "Headphone sem fio com áudio potente, conforto prolongado e excelente autonomia para rotina intensa.",
  linkAfiliado: "https://meli.la/1m73aLf",
  meliId: "MLB25230109",
},

{
  id: 25,
  nome: "Wave Buds 2 TWS",
  categoria: "Tecnologia",
  preco: "R$ 264,00",
  precoNumero: 264,
  estrelas: 4.7,
  descricaoCurta: "Compacto, moderno e pronto para o dia a dia.",
  descricaoLonga: "Fone Bluetooth com encaixe confortável, carregamento prático e áudio limpo para músicas e chamadas.",
  linkAfiliado: "https://meli.la/2KJaBke",
  meliId: "MLB44895127",
},

{
  id: 26,
  nome: "Philips TWS Sem Fio",
  categoria: "Tecnologia",
  preco: "R$ 132,22",
  precoNumero: 132.22,
  estrelas: 4.7,
  descricaoCurta: "Qualidade Philips com conforto diário.",
  descricaoLonga: "Fone Bluetooth leve, confiável e com som equilibrado para trabalho, estudo e lazer.",
  linkAfiliado: "https://meli.la/1Bbj5cx",
  meliId: "MLB38480851",
},

{
  id: 27,
  nome: "Fone Bluetooth Inova",
  categoria: "Tecnologia",
  preco: "R$ 68,64",
  precoNumero: 68.64,
  estrelas: 4.5,
  descricaoCurta: "Econômico, prático e funcional.",
  descricaoLonga: "Modelo ideal para chamadas, músicas e uso casual com boa autonomia e conexão simples.",
  linkAfiliado: "https://meli.la/1UPNKaA",
  meliId: "MLB63184370",
},

{
  id: 28,
  nome: "Fone Philips Bluetooth",
  categoria: "Tecnologia",
  preco: "R$ 115,00",
  precoNumero: 115,
  estrelas: 4.7,
  descricaoCurta: "Marca confiável e áudio limpo.",
  descricaoLonga: "Fone sem fio com bom encaixe, som claro e uso confortável para várias horas.",
  linkAfiliado: "https://meli.la/1bQ1vYd",
  meliId: "MLB6487448300",
},

{
  id: 29,
  nome: "Xiaomi Redmi Buds 6 Play",
  categoria: "Tecnologia",
  preco: "R$ 98,76",
  precoNumero: 98.76,
  estrelas: 4.8,
  descricaoCurta: "Leve, moderno e ótima bateria.",
  descricaoLonga: "Fone Bluetooth Xiaomi com conexão rápida, conforto no ouvido e excelente custo-benefício.",
  linkAfiliado: "https://meli.la/2Gb9Zkf",
  meliId: "MLB4050375603",
},

{
  id: 30,
  nome: "Hivi Bluetooth TWS",
  categoria: "Tecnologia",
  preco: "R$ 24,98",
  precoNumero: 24.98,
  estrelas: 4.4,
  descricaoCurta: "Design moderno e som potente.",
  descricaoLonga: "Fone sem fio com boa autonomia, encaixe seguro e áudio forte para rotina diária.",
  linkAfiliado: "https://meli.la/2ACyRBR",
  meliId: "MLB4403213005",
},

{
  id: 31,
  nome: "QCY HT05 ANC Melobuds",
  categoria: "Tecnologia",
  preco: "R$ 269,90",
  precoNumero: 269.9,
  estrelas: 4.9,
  descricaoCurta: "Cancelamento de ruído e som premium.",
  descricaoLonga: "Modelo avançado com ANC, graves intensos e ótima qualidade para música e chamadas.",
  linkAfiliado: "https://meli.la/1fDX9ra",
  meliId: "MLB19897574",
},

{
  id: 32,
  nome: "QCY N30 ANC",
  categoria: "Tecnologia",
  preco: "R$ 169,00",
  precoNumero: 169,
  estrelas: 4.8,
  descricaoCurta: "Silêncio externo e foco total.",
  descricaoLonga: "Fone com cancelamento ativo de ruído, conexão estável e excelente experiência sonora.",
  linkAfiliado: "https://meli.la/2555XaM",
  meliId: "MLB47588999",
},

{
  id: 33,
  nome: "Awei T29 Bluetooth",
  categoria: "Tecnologia",
  preco: "R$ 109,90",
  precoNumero: 109.9,
  estrelas: 4.6,
  descricaoCurta: "Compacto, bonito e eficiente.",
  descricaoLonga: "Fone sem fio com áudio limpo, microfone integrado e bateria ideal para o dia.",
  linkAfiliado: "https://meli.la/1eACX2S",
  meliId: "MLB4231695745",
},

{
  id: 34,
  nome: "Headphone Dapon H02d",
  categoria: "Tecnologia",
  preco: "R$ 78,90",
  precoNumero: 78.9,
  estrelas: 4.5,
  descricaoCurta: "Conforto e som encorpado.",
  descricaoLonga: "Headphone Bluetooth com hastes ajustáveis e áudio forte para músicas, vídeos e games.",
  linkAfiliado: "https://meli.la/2ZYktS1",
  meliId: "MLB24117280",
},

{
  id: 35,
  nome: "Fone Bluetooth Gancho",
  categoria: "Tecnologia",
  preco: "R$ 49,97",
  precoNumero: 49.97,
  estrelas: 4.4,
  descricaoCurta: "Fixação firme para treino.",
  descricaoLonga: "Ideal para academia e corrida. Gancho auricular que mantém estabilidade em movimento.",
  linkAfiliado: "https://meli.la/2XeFXR7",
  meliId: "MLB67713448",
},

{
  id: 36,
  nome: "Anker P30i Bluetooth",
  categoria: "Tecnologia",
  preco: "R$ 208,22",
  precoNumero: 208.22,
  estrelas: 4.8,
  descricaoCurta: "Marca premium com áudio forte.",
  descricaoLonga: "Fone moderno com ótima bateria, microfones eficientes e qualidade sonora superior.",
  linkAfiliado: "https://meli.la/18XVphQ",
  meliId: "MLB38176139",
},

{
  id: 37,
  nome: "F9-5 Bluetooth TWS",
  categoria: "Tecnologia",
  preco: "R$ 24,99",
  precoNumero: 24.99,
  estrelas: 4.3,
  descricaoCurta: "Popular, funcional e acessível.",
  descricaoLonga: "Modelo conhecido pelo custo-benefício, boa autonomia e estojo carregador prático.",
  linkAfiliado: "https://meli.la/1RRNYqG",
  meliId: "MLB6594579826",
},

{
  id: 38,
  nome: "Basike Open Ear Clipe",
  categoria: "Tecnologia",
  preco: "R$ 189,81",
  precoNumero: 189.81,
  estrelas: 4.7,
  descricaoCurta: "Escute sem tampar o ouvido.",
  descricaoLonga: "Design aberto com conforto prolongado e mais percepção do ambiente ao redor.",
  linkAfiliado: "https://meli.la/2ScieQt",
  meliId: "MLB53767753",
},

{
  id: 39,
  nome: "Eletro Mex Bluetooth",
  categoria: "Tecnologia",
  preco: "R$ 61,38",
  precoNumero: 61.38,
  estrelas: 4.4,
  descricaoCurta: "Simples, leve e funcional.",
  descricaoLonga: "Fone sem fio ideal para chamadas, músicas e uso casual diário.",
  linkAfiliado: "https://meli.la/2Lr2q1f",
  meliId: "MLB4396849375",
},

{
  id: 40,
  nome: "Fone Bluetooth 5.4",
  categoria: "Tecnologia",
  preco: "R$ 49,72",
  precoNumero: 49.72,
  estrelas: 4.5,
  descricaoCurta: "Conexão rápida e estável.",
  descricaoLonga: "Tecnologia Bluetooth 5.4 com menor atraso e melhor eficiência energética.",
  linkAfiliado: "https://meli.la/1c9bcW2",
  meliId: "MLB5758097762",
},

{
  id: 41,
  nome: "Fone Gamer RGB Bluetooth",
  categoria: "Tecnologia",
  preco: "R$ 47,43",
  precoNumero: 47.43,
  estrelas: 4.4,
  descricaoCurta: "Visual gamer e som imersivo.",
  descricaoLonga: "Modelo com LED RGB, áudio potente e estilo ideal para games, vídeos e música.",
  linkAfiliado: "https://meli.la/1h6oToY",
  meliId: "MLB4561064919",
},
];

export const categorias = [
  "Tecnologia",
  "Casa",
  "Cozinha",
  "Beleza",
  "Fitness",
  "Automotivo",
  "Escritorio",
  "Utilidades"
];
